import { CandidateProfile, EmployerProfile, Job, Application, SimulatedEmail } from '../types';

export const INITIAL_EMPLOYERS: EmployerProfile[] = [
  {
    id: 'emp-01',
    companyName: 'AeroSys Dynamics',
    legalEntity: 'AeroSys Dynamics Corporation LLC',
    corporateDomain: 'aerosysdynamics.com',
    contactEmail: 'talent.plm@aerosysdynamics.com',
    adminEmail: 'security@aerosysdynamics.com',
    contactPerson: 'David Vance',
    contactTitle: 'VP of Digital Engineering',
    industry: 'Aerospace & Defense',
    headquarters: 'Seattle, WA, USA',
    companySize: '2,500 - 5,000 employees',
    website: 'https://aerosysdynamics.com',
    primaryPLMStack: ['Siemens Teamcenter', 'Dassault 3DEXPERIENCE / ENOVIA'],
    cadEnvironments: ['Siemens NX', 'CATIA V5/V6'],
    verificationStatus: 'verified',
    verificationRequestedAt: '2026-09-10T10:14:00Z',
    verifiedAt: '2026-09-11T14:30:00Z',
    taxRegistrationNumber: 'EIN-84-2918402',
    verificationDocName: 'DoD_CMMC_Level2_AeroSys_Certificate.pdf',
    about: 'Prime defense & aerospace aerostructures supplier. We operate an enterprise Siemens Teamcenter 14 active workspace environment with full ITAR compliance and multi-CAD NX integration.',
    logoInitials: 'AD',
    logoBg: 'bg-blue-900',
  },
  {
    id: 'emp-02',
    companyName: 'MedDevice Biosolutions',
    legalEntity: 'MedDevice Biosolutions Inc.',
    corporateDomain: 'meddevicebio.com',
    contactEmail: 'engineering-recruiting@meddevicebio.com',
    adminEmail: 'it-admin@meddevicebio.com',
    contactPerson: 'Claire Hoffmann',
    contactTitle: 'Head of PLM & Quality Systems',
    industry: 'Medical Technology',
    headquarters: 'Boston, MA, USA',
    companySize: '500 - 1,000 employees',
    website: 'https://meddevicebio.com',
    primaryPLMStack: ['PTC Windchill', 'Arena PLM'],
    cadEnvironments: ['PTC Creo', 'SolidWorks'],
    verificationStatus: 'verified',
    verificationRequestedAt: '2026-09-14T09:20:00Z',
    verifiedAt: '2026-09-15T11:00:00Z',
    taxRegistrationNumber: 'EIN-04-8839201',
    verificationDocName: 'FDA_21CFR_Part11_Audit_Attestation.pdf',
    about: 'Class III surgical robotics and diagnostic devices. Operating certified PTC Windchill 13 environment with ISO 13485 design history file (DHF) and CAPA closed-loop workflows.',
    logoInitials: 'MB',
    logoBg: 'bg-emerald-900',
  },
  {
    id: 'emp-03',
    companyName: 'Apex Turbomachinery',
    legalEntity: 'Apex Turbomachinery Propulsion Systems Ltd.',
    corporateDomain: 'apexturbo.aero',
    contactEmail: 'plm-careers@apexturbo.aero',
    adminEmail: 'cto-office@apexturbo.aero',
    contactPerson: 'Karan Patel',
    contactTitle: 'Senior Director of Enterprise PLM',
    industry: 'Aerospace & Defense',
    headquarters: 'Denver, CO, USA',
    companySize: '1,200 - 2,500 employees',
    website: 'https://apexturbo.aero',
    primaryPLMStack: ['Siemens Teamcenter', 'Aras Innovator'],
    cadEnvironments: ['Siemens NX'],
    verificationStatus: 'pending_verification',
    verificationRequestedAt: '2026-09-24T18:40:00Z',
    taxRegistrationNumber: 'EIN-81-9923812',
    verificationDocName: 'Apex_Corporate_Tax_Govt_Contractor_Proof.pdf',
    about: 'Hypersonic turbine and commercial aerospace propulsion developer. Transitioning legacy PDM to Teamcenter Active Workspace 6.2 with Aras engineering bill of materials linkage.',
    logoInitials: 'AT',
    logoBg: 'bg-amber-800',
  },
  {
    id: 'emp-04',
    companyName: 'Valo EV Mobility',
    legalEntity: 'Valo Mobility Technologies GmbH',
    corporateDomain: 'valomobility.de',
    contactEmail: 'hr@valomobility.de',
    adminEmail: 'plm-ops@valomobility.de',
    contactPerson: 'Stefan Richter',
    contactTitle: 'PLM Architecture Lead',
    industry: 'Automotive & EV',
    headquarters: 'Munich, Germany',
    companySize: '3,000 - 6,000 employees',
    website: 'https://valomobility.de',
    primaryPLMStack: ['Dassault 3DEXPERIENCE / ENOVIA', 'Siemens Teamcenter'],
    cadEnvironments: ['CATIA V5/V6'],
    verificationStatus: 'under_review',
    verificationRequestedAt: '2026-09-23T14:10:00Z',
    taxRegistrationNumber: 'DE-HRB-894211',
    verificationDocName: 'Munich_Commercial_Register_Excerpt.pdf',
    about: 'Next-gen electric vehicle platform architecture. Deployed Dassault 3DEXPERIENCE cloud for body-in-white and battery pack change governance.',
    logoInitials: 'VM',
    logoBg: 'bg-slate-800',
  },
];

export const INITIAL_CANDIDATE: CandidateProfile = {
  id: 'cand-01',
  name: 'Marcus Vance',
  headline: 'Principal PLM Solution Architect | Siemens Teamcenter 14 & Active Workspace | ITAR Cleared',
  email: 'marcus.vance.plm@proton.me',
  phone: '+1 (206) 555-0192',
  location: 'Seattle, WA (Open to Remote / Hybrid)',
  yearsOfExperience: 11,
  primaryPLM: 'Siemens Teamcenter',
  secondaryPLMs: ['Dassault 3DEXPERIENCE / ENOVIA', 'Aras Innovator'],
  modules: [
    'BOM & Part Architecture',
    'Active Workspace (AWC)',
    'CAD / MCAD Integration',
    'Engineering Change (ECN/ECO)',
    'Data Migration & ETL',
  ],
  cadTools: ['Siemens NX', 'CATIA V5/V6'],
  clearance: 'ITAR / Export Controlled',
  certifications: [
    'Siemens Certified Professional: Teamcenter 14 System Architecture',
    'Siemens Active Workspace Customization Expert',
    'DoD Defense Security Service (DSS) Clearance Verification',
  ],
  currentCompany: 'Raytheon Technologies (Contract)',
  currentRole: 'Lead PLM Migration Specialist',
  expectedCompensation: '$180,000 - $210,000 / yr (or $115/hr C2C)',
  availableFrom: '2 Weeks Notice',
  bio: '11+ years designing, architecting, and migrating mission-critical PLM deployments across aerospace, defense, and high-tech manufacturing. Deep expertise in Active Workspace client configuration, ITK/C++ custom handlers, BMIDE data modeling, Dispatcher CAD translation pipelines, and SAP ERP BOM reconciliation.',
  verifiedSpecialist: true,
  avatarInitials: 'MV',
  accentColor: 'bg-slate-900',
  portfolioProjects: [
    {
      title: 'Aerospace Multi-Site Teamcenter 14 Active Workspace Upgrade',
      system: 'Siemens Teamcenter 14.2 & Active Workspace 6.2',
      description: 'Led end-to-end architecture upgrade for 3,400 concurrent global CAD engineering seats across 4 continents.',
      impact: 'Cut CAD check-in/out latency by 44% and automated 18 legacy ECN change notice approval routing steps.',
    },
    {
      title: 'Legacy SmarTeam & MatrixOne to 3DEXPERIENCE Data Migration',
      system: 'Dassault 3DEXPERIENCE & CATIA V5',
      description: 'Built automated ETL validation scripts for 1.8M legacy CAD revisions, assembly hierarchies, and engineering change histories.',
      impact: 'Zero data loss during transition with 100% ITAR compliance sign-off.',
    },
  ],
};

export const INITIAL_JOBS: Job[] = [
  {
    id: 'job-01',
    employerId: 'emp-01',
    employerName: 'AeroSys Dynamics',
    employerLogoInitials: 'AD',
    employerLogoBg: 'bg-blue-900',
    isEmployerVerified: true,
    title: 'Lead Siemens Teamcenter 14 Architecture Specialist',
    primaryPLM: 'Siemens Teamcenter',
    relatedSystems: ['Dassault 3DEXPERIENCE / ENOVIA'],
    requiredModules: [
      'Active Workspace (AWC)',
      'BOM & Part Architecture',
      'Engineering Change (ECN/ECO)',
      'CAD / MCAD Integration',
    ],
    cadIntegration: ['Siemens NX', 'CATIA V5/V6'],
    experienceLevel: 'Lead / Architect (8+ yrs)',
    employmentType: 'Full-Time Permanent',
    workplaceType: 'Hybrid',
    location: 'Seattle, WA (Relocation Assistance Provided)',
    compensation: {
      min: 175000,
      max: 205000,
      currency: 'USD',
      period: 'yearly',
    },
    itarRequired: true,
    clearanceRequired: 'ITAR / Export Controlled',
    summary: 'AeroSys Dynamics is seeking a Principal Siemens Teamcenter Solutions Architect to oversee the enterprise digital thread for our next-generation composite aerostructures program.',
    responsibilities: [
      'Lead BMIDE data model extensions, schema refactoring, and Active Workspace 6.x configuration.',
      'Architect high-availability Dispatcher servers and 4-tier deployment topology across hybrid AWS GovCloud.',
      'Develop custom ITK handlers, RAC plugins, and SOA REST endpoints for ERP and MES synchronization.',
      'Enforce defense export compliance (ITAR/EAR) security marking rules inside Access Manager.',
    ],
    requirements: [
      '8+ years dedicated PLM implementation experience with Siemens Teamcenter.',
      'Demonstrated expertise with Teamcenter BMIDE, Active Workspace, and Siemens NX integration.',
      'U.S. Citizenship or Permanent Resident status required for ITAR defense program.',
      'Strong hands-on mastery of C++, Java SOA, and Active Workspace TypeScript/Angular framework.',
    ],
    postedAt: '2026-09-22T08:00:00Z',
    status: 'active',
    applicantCount: 7,
  },
  {
    id: 'job-02',
    employerId: 'emp-02',
    employerName: 'MedDevice Biosolutions',
    employerLogoInitials: 'MB',
    employerLogoBg: 'bg-emerald-900',
    isEmployerVerified: true,
    title: 'Senior PTC Windchill Administrator & Regulatory PLM Specialist',
    primaryPLM: 'PTC Windchill',
    relatedSystems: ['Arena PLM'],
    requiredModules: [
      'Quality & CAPA',
      'Engineering Change (ECN/ECO)',
      'CAD / MCAD Integration',
      'Requirements & MBSE',
    ],
    cadIntegration: ['PTC Creo', 'SolidWorks'],
    experienceLevel: 'Mid-Senior (4-7 yrs)',
    employmentType: 'Full-Time Permanent',
    workplaceType: 'Remote',
    location: 'United States (Remote)',
    compensation: {
      min: 145000,
      max: 170000,
      currency: 'USD',
      period: 'yearly',
    },
    itarRequired: false,
    clearanceRequired: 'None',
    summary: 'Join MedDevice Biosolutions to administer our enterprise PTC Windchill PDMLink 13 platform supporting FDA Class II & III cardiovascular robotics device lifecycles.',
    responsibilities: [
      'Maintain PTC Windchill 13.x system uptime, patch cycles, cluster failover, and replica vaults.',
      'Configure Windchill Change Management (WTChangeRequest2, WTChangeOrder2) aligned with 21 CFR Part 11 electronic signatures.',
      'Optimize Creo Workgroup Manager (WGM) performance for large medical CAD assemblies.',
      'Collaborate with Quality Engineering to automate CAPA and DHF audit trail extractions.',
    ],
    requirements: [
      '4+ years hands-on administration of PTC Windchill PDMLink.',
      'Familiarity with medical device regulatory requirements (ISO 13485, FDA CFR Part 820).',
      'Experience with Info*Engine tasks, Windchill shell utilities (windchill wt.load.LoadFromFile), and Oracle/SQL Server tuning.',
    ],
    postedAt: '2026-09-23T12:30:00Z',
    status: 'active',
    applicantCount: 4,
  },
  {
    id: 'job-03',
    employerId: 'emp-01',
    employerName: 'AeroSys Dynamics',
    employerLogoInitials: 'AD',
    employerLogoBg: 'bg-blue-900',
    isEmployerVerified: true,
    title: 'PLM CAD & BOM Migration Consultant (Contract C2C)',
    primaryPLM: 'Siemens Teamcenter',
    relatedSystems: ['Aras Innovator', 'PTC Windchill'],
    requiredModules: [
      'Data Migration & ETL',
      'BOM & Part Architecture',
      'CAD / MCAD Integration',
    ],
    cadIntegration: ['Siemens NX', 'SolidWorks'],
    experienceLevel: 'Mid-Senior (4-7 yrs)',
    employmentType: 'Contract (W2/C2C)',
    workplaceType: 'Remote',
    location: 'Remote (US Timezones)',
    compensation: {
      min: 95,
      max: 125,
      currency: 'USD',
      period: 'hourly',
    },
    itarRequired: true,
    clearanceRequired: 'ITAR / Export Controlled',
    summary: '6-month extendable contract assisting our enterprise migration of 450,000 legacy CAD models, drawing sheets, and product structures into Teamcenter 14.',
    responsibilities: [
      'Write ETL scripts using tcxml_import / plmxml_export and custom Python data scrubbers.',
      'Validate assembly bounding boxes, missing reference parts, and duplicate part revisions.',
      'Execute reconciliation reports between legacy PDM metadata and BMIDE attributes.',
    ],
    requirements: [
      'Deep hands-on experience with Siemens PLMXML, TcXML, and Teamcenter command-line utilities.',
      'Proven background in enterprise data hygiene and CAD model migration.',
      'ITAR eligibility mandatory.',
    ],
    postedAt: '2026-09-24T10:15:00Z',
    status: 'active',
    applicantCount: 12,
  },
  {
    id: 'job-04',
    employerId: 'emp-03',
    employerName: 'Apex Turbomachinery',
    employerLogoInitials: 'AT',
    employerLogoBg: 'bg-amber-800',
    isEmployerVerified: false,
    title: 'Lead Aras Innovator & BOM Automation Specialist (Awaiting Verification)',
    primaryPLM: 'Aras Innovator',
    relatedSystems: ['Siemens Teamcenter'],
    requiredModules: [
      'BOM & Part Architecture',
      'Engineering Change (ECN/ECO)',
      'Supplier Collaboration',
    ],
    cadIntegration: ['Siemens NX'],
    experienceLevel: 'Lead / Architect (8+ yrs)',
    employmentType: 'Full-Time Permanent',
    workplaceType: 'Onsite',
    location: 'Denver, CO, USA',
    compensation: {
      min: 160000,
      max: 185000,
      currency: 'USD',
      period: 'yearly',
    },
    itarRequired: true,
    clearanceRequired: 'ITAR / Export Controlled',
    summary: 'Build and deploy our multi-tier Bill of Materials (EBOM to MBOM) synchronization engine connecting Aras Innovator with our shop-floor Siemens NX assemblies.',
    responsibilities: [
      'Develop custom Aras server methods (C# .NET) and client-side JavaScript forms.',
      'Implement automated ECO lifecycle transitions and supplier drawing export watermarking.',
    ],
    requirements: [
      'Aras Certified Solutions Consultant certification preferred.',
      '5+ years with Aras Innovator ItemTypes, Lifecycles, Workflows, and AML queries.',
    ],
    postedAt: '2026-09-24T18:45:00Z',
    status: 'pending_verification',
    applicantCount: 0,
  },
];

export const INITIAL_APPLICATIONS: Application[] = [
  {
    id: 'app-01',
    jobId: 'job-01',
    jobTitle: 'Lead Siemens Teamcenter 14 Architecture Specialist',
    employerId: 'emp-01',
    employerName: 'AeroSys Dynamics',
    candidateId: 'cand-01',
    candidateName: 'Marcus Vance',
    candidateEmail: 'marcus.vance.plm@proton.me',
    candidateHeadline: 'Principal PLM Solution Architect | Siemens Teamcenter 14 & Active Workspace',
    candidatePrimaryPLM: 'Siemens Teamcenter',
    candidateExperience: 11,
    matchScore: 98,
    appliedDate: '2026-09-23T15:20:00Z',
    coverNote: 'Hello David, I have 11 years architecting Teamcenter 14 & Active Workspace enterprise deployments with strict ITAR compliance. I recently completed a 3,400-seat multi-site upgrade cutting CAD checkout latency by 44%. I would love to discuss how I can support AeroSys Dynamics.',
    resumeFileName: 'Marcus_Vance_PLM_Architect_Resume.pdf',
    status: 'technical_interview',
    internalNotes: 'Strongest Teamcenter candidate in the pipeline. Excellent BMIDE and ITAR compliance credentials. Scheduled for Tech Deep Dive.',
  },
  {
    id: 'app-02',
    jobId: 'job-03',
    jobTitle: 'PLM CAD & BOM Migration Consultant (Contract C2C)',
    employerId: 'emp-01',
    employerName: 'AeroSys Dynamics',
    candidateId: 'cand-01',
    candidateName: 'Marcus Vance',
    candidateEmail: 'marcus.vance.plm@proton.me',
    candidateHeadline: 'Principal PLM Solution Architect | Siemens Teamcenter 14 & Active Workspace',
    candidatePrimaryPLM: 'Siemens Teamcenter',
    candidateExperience: 11,
    matchScore: 95,
    appliedDate: '2026-09-24T11:00:00Z',
    coverNote: 'Extensive hands-on mastery of tcxml_import, PLMXML, and complex CAD relationship mapping for aerospace defense programs.',
    resumeFileName: 'Marcus_Vance_PLM_Architect_Resume.pdf',
    status: 'screening',
    internalNotes: 'Over-qualified for pure migration contract, but excellent candidate if willing to take short term advisory role.',
  },
  {
    id: 'app-03',
    jobId: 'job-02',
    jobTitle: 'Senior PTC Windchill Administrator & Regulatory PLM Specialist',
    employerId: 'emp-02',
    employerName: 'MedDevice Biosolutions',
    candidateId: 'cand-02',
    candidateName: 'Elena Rostova',
    candidateEmail: 'elena.rostova@engineer.net',
    candidateHeadline: 'Lead PTC Windchill & Creo Migration Engineer | 8 yrs FDA DHF Experience',
    candidatePrimaryPLM: 'PTC Windchill',
    candidateExperience: 8,
    matchScore: 94,
    appliedDate: '2026-09-24T08:45:00Z',
    coverNote: 'Hi Claire, I manage PTC Windchill PDMLink 12/13 across 2 global medical dev facilities, including automated DHF traceability.',
    resumeFileName: 'Elena_Rostova_Windchill_Resume.pdf',
    status: 'screening',
    internalNotes: 'Very solid Windchill 13 and ISO 13485 experience. Ready for initial hiring manager call.',
  },
];

export const INITIAL_SIMULATED_EMAILS: SimulatedEmail[] = [
  {
    id: 'mail-01',
    to: 'admin@plmnexus.internal',
    from: 'system@plmnexus.internal',
    subject: '[ACTION REQUIRED] New PLM Employer Registered: Apex Turbomachinery (Pending Verification)',
    body: `Hello Platform Governance Administrator,

A new corporate enterprise has registered on PLM Nexus and requested Enterprise Verification:

Company Name: Apex Turbomachinery Propulsion Systems Ltd.
Legal Entity: Apex Turbomachinery Propulsion Systems Ltd.
Domain: apexturbo.aero (Corporate MX Records Verified)
Contact Person: Karan Patel (Senior Director of Enterprise PLM)
Contact Email: plm-careers@apexturbo.aero
Tax Registration / EIN: EIN-81-9923812
Submitted Document: Apex_Corporate_Tax_Govt_Contractor_Proof.pdf
Declared PLM Stack: Siemens Teamcenter, Aras Innovator (NX CAD)
Reason / Job Planned: Lead Aras Innovator & BOM Automation Specialist

Until verified by you, Apex Turbomachinery cannot publish live job postings or contact registered PLM candidates.

Please review this enterprise in the Main Admin Verification Console.`,
    timestamp: '2026-09-24T18:40:05Z',
    triggerEvent: 'employer_registration',
    read: false,
    metadata: {
      companyId: 'emp-03',
    },
  },
  {
    id: 'mail-02',
    to: 'plm-careers@apexturbo.aero',
    from: 'governance@plmnexus.internal',
    subject: 'Verification Request Received - Your PLM Nexus Enterprise Account is Under Review',
    body: `Dear Karan Patel,

Thank you for registering Apex Turbomachinery on PLM Nexus - The Dedicated Network for Product Lifecycle Management Engineers.

Your enterprise verification request and corporate credentials have been dispatched to our Main Platform Governance Administrator for review.

What happens next:
1. The Main Admin verifies your corporate domain (apexturbo.aero), business registration (EIN-81-9923812), and active PLM ecosystem credentials.
2. Once approved, you will receive an instant confirmation email and your job posting capabilities will be unlocked immediately.
3. Your posted positions will display the "Verified PLM Enterprise" trust badge to certified Teamcenter, Windchill, and 3DEXPERIENCE engineers.

Typical review turnaround is under 2 hours during normal business operating hours.`,
    timestamp: '2026-09-24T18:40:10Z',
    triggerEvent: 'employer_registration',
    read: true,
    metadata: {
      companyId: 'emp-03',
    },
  },
  {
    id: 'mail-03',
    to: 'talent.plm@aerosysdynamics.com',
    from: 'governance@plmnexus.internal',
    subject: 'Enterprise Account Verified: AeroSys Dynamics Corporation LLC',
    body: `Dear David Vance,

Congratulations! Your enterprise verification request for AeroSys Dynamics Corporation LLC has been approved by the PLM Nexus Admin.

Your company is now recognized as a Verified PLM Enterprise with ITAR export compliance credentials. You can now:
• Publish unconstrained PLM positions across Teamcenter, Windchill, and 3DEXPERIENCE pipelines.
• Directly access certified candidate portfolios and schedule technical screenings.
• Manage applicants through your private ATS pipeline.`,
    timestamp: '2026-09-11T14:30:15Z',
    triggerEvent: 'admin_company_approved',
    read: true,
    metadata: {
      companyId: 'emp-01',
    },
  },
];
